import { ethers } from "hardhat";
import fs from "node:fs";
import path from "node:path";

async function main() {
  const [deployer] = await ethers.getSigners();

  const Token = await ethers.getContractFactory("KryptaFlowToken");
  const token = await Token.deploy();
  await token.waitForDeployment();

  console.log("Deployer:", deployer.address);
  console.log("KFL Token:", await token.getAddress());

  const outDir = path.resolve(__dirname, "..", "..", "apps", "web", "app", "generated");
  fs.mkdirSync(outDir, { recursive: true });

  const outFile = path.join(outDir, "chain.ts");
  const contents = `/* eslint-disable */
// This file is auto-generated by chain/scripts/deploy.ts
export const KRYPTAFLOW = {
  chainIdDec: 31337,
  chainIdHex: "0x7a69",
  rpcUrl: "http://127.0.0.1:8545",
  tokenAddress: "${await token.getAddress()}",
} as const;
`;
  fs.writeFileSync(outFile, contents, "utf8");
  console.log("Wrote:", outFile);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});

